# Use an official Node.js runtime as a parent image
FROM node:18-alpine AS node1

# Set the working directory to /app
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install dependencies
RUN npm install && \
    npm install -g serve && \
    npm run build

# Copy the rest of the app's source code to the container
COPY . .

# Start the app
CMD ["npm", "run", "serve"]