version: 2.1

jobs:
  my-job:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
      - run: npm test

workflows:
  my-workflow:
    jobs:
      - my-job