version: 2.1

jobs:
  our-job:
    docker:
      - image: cimg/node:20.12.2
    steps:
      - checkout
      - run: npm install
      - run: npm test

workflows:
  my-workflow:
    jobs:
      - our-job